# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t my-docker-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag my-docker-app ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull Docker image from Docker Hub
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest

    - name: Deploy Docker container
      run: |
        docker stop my-docker-app || true
        docker rm my-docker-app || true
        docker run -d --name my-docker-app -p 4500:4500 ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest

    - name: Wait for application to start
      run: sleep 90  # Adjust sleep time if necessary

    - name: Test application
      run: curl -f http://localhost:4500 || exit 1

