# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build . -t my-docker-app:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag my-docker-app:latest ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest

  deploy-and-test:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy application
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest
        docker run -d -p 4500:4500 --name my-docker-app ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest
    
    - name: Show logs
      run: docker logs my-docker-app

    - name: Wait for application to start
      run: sleep 90  # Adjust as necessary

    - name: Test application
      run: |
        curl -f http://localhost:4500 || exit 1
        curl -f http://localhost:4500/health || exit 1

